# Generated by Django 4.0.7 on 2022-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0003_booking_number_guests_booking_number_rooms_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stay',
            field=models.CharField(default='Swartskaap', max_length=13),
            preserve_default=False,
        ),
    ]
